// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"8fa217f8a37cb8eaf60ec7709475e0b0c53731c8c41f5b4608f34875788499c9d1c37dcbb0408dd4b41d31b15a0c5ee81784de076e2e0972c924109bc2921ecd"}}
];
